INSERT INTO  PERSON VALUES(1,'!265@AcbdA&') ;
INSERT INTO  USER_PASS_HISTORY VALUES(1, 1 ,'!265@AcbdA&' , GETDATE()) ;


UPDATE PERSON
SET PASSWORD='!265@AcbdA'
WHERE ID=1;

UPDATE PERSON
SET PASSWORD='!265@AcbdAGG'
WHERE ID=1;

