CREATE TABLE PERSON(
    ID INT PRIMARY KEY,
    PASSWORD NVARCHAR(1000),
    NAME VARCHAR(100) NOT NULL)
   
CREATE TABLE USER_PASS_HISTORY(
    USER_ID INT ,
    OLD_PASSWORD NVARCHAR(1000) NOT NULL,
    DATE_MODIFIED DATETIME NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES PERSON(ID)
)

INSERT INTO  PERSON VALUES(1, 'Thanasis' , '!265@AcbdA&') ;

DROP TRIGGER IF EXISTS new_pass_insert;
GO
CREATE TRIGGER new_pass_insert ON PERSON AFTER INSERT 
AS BEGIN
INSERT INTO USER_PASS_HISTORY VALUES(dbo.PERSON.ID , '!265@AcbdA&', GETDATE());
END; 

SELECT * FROM PERSON
SELECT * FROM USER_PASS_HISTORY