CREATE TABLE PERSON(
    ID INT PRIMARY KEY,
    PASSWORD NVARCHAR(1000),
    NAME VARCHAR(100) NOT NULL)
   
CREATE TABLE USER_PASS_HISTORY(
    HISTORY_ID INT,
    USER_ID INT FOREIGN KEY REFERENCES PERSON(ID),
    OLD_PASSWORD NVARCHAR(1000) NOT NULL,
    DATE_MODIFIED DATETIME NOT NULL 
)

DROP TRIGGER IF EXISTS new_pass_insert;
GO
CREATE TRIGGER new_pass_insert ON PERSON AFTER INSERT 
AS BEGIN
DECLARE @user_id int  , @old_pass NVARCHAR(1000)
    SELECT @user_id = PERSON.ID  , @old_pass = PERSON.[PASSWORD] FROM PERSON
    INSERT INTO USER_PASS_HISTORY VALUES(1, @user_id  , @old_pass, GETDATE());      
END; 

INSERT INTO  PERSON VALUES(1, '!265@AcbdA&' , 'Thanasis') ;

SELECT * FROM PERSON
SELECT * FROM USER_PASS_HISTORY

DELETE FROM PERSON
DELETE FROM USER_PASS_HISTORY